version: '3.8'

services:
  advisor:
    build:
      context: .
      dockerfile: Dockerfile
    image: football-betting-advisor
    container_name: football-betting-advisor
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: football-betting-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

volumes:
  redis-data:
    driver: local 